# Generated by Django 4.0 on 2021-12-27 07:06

import Blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Blog', '0002_remove_post_time_remove_post_category_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to=Blog.models.upload_image_path)),
                ('url_price', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules',
                                           to='Blog.post')),
            ],
        ),
    ]
