# Generated by Django 4.0 on 2021-12-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Blog', '0004_rename_module_postmodule_disadvantagesmodule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disadvantagesmodule',
            name='post_module',
        ),
        migrations.AddField(
            model_name='postmodule',
            name='advantages',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='postmodule',
            name='disadvantages',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='AdvantagesModule',
        ),
        migrations.DeleteModel(
            name='DisadvantagesModule',
        ),
    ]
