# Generated by Django 4.0 on 2021-12-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Blog', '0005_remove_disadvantagesmodule_post_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodule',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
